import { WardrobeItem } from './database';

/**
 * Normalized weather context for outfit generation
 * 
 * This interface represents weather data that has been processed into
 * actionable bands and flags for the outfit generation algorithm.
 */
export interface WeatherContext {
  // Temperature classification (exactly one should be true)
  isCold: boolean;      // < 55°F
  isMild: boolean;      // 55-75°F
  isWarm: boolean;      // 75-90°F
  isHot: boolean;       // >= 90°F
  
  // Precipitation
  isRainLikely: boolean; // >= 35% chance
  
  // Temperature swing
  dailySwing: number;    // high - low (in °F)
  hasLargeSwing: boolean; // >= 20°F
  
  // Target warmth level (0-3)
  // 0 = minimal coverage (hot weather)
  // 1 = light layering (warm weather)
  // 2 = moderate layering (mild weather)
  // 3 = heavy layering (cold weather)
  targetWeight: number;
  
  // Raw values for reference
  currentTemp: number;
  highTemp: number;
  lowTemp: number;
  precipChance: number; // 0-1
}

/**
 * Color classification from explicit color field
 * 
 * Colors are stored explicitly in the database color field.
 * 'unknown' is used when color is null or empty.
 */
export type ColorCategory = 
  | 'black' | 'white' | 'grey' | 'charcoal' | 'ivory' | 'cream' | 'beige' | 'taupe' | 'stone'
  | 'navy' | 'blue' | 'light-blue' | 'sky-blue' | 'teal'
  | 'brown' | 'tan' | 'khaki' | 'camel' | 'chocolate'
  | 'green' | 'olive' | 'forest' | 'sage'
  | 'red' | 'burgundy' | 'maroon' | 'rust'
  | 'yellow' | 'mustard'
  | 'pink' | 'blush' | 'purple' | 'lavender'
  | 'denim' | 'multicolor'
  | 'unknown';

/**
 * Formality band classification
 * 
 * Derived from formality_score:
 * - casual: 1-3
 * - smart-casual: 4-6
 * - refined: 7-10
 */
export type FormalityBand = 'casual' | 'smart-casual' | 'refined';

/**
 * Item with enriched metadata for generation
 * 
 * Extends WardrobeItem with computed properties used by the
 * outfit generation algorithm.
 */
export interface EnrichedItem extends WardrobeItem {
  color: ColorCategory; // Explicit color from WardrobeItem.color field
  formalityBand: FormalityBand;
  weatherWeight: number; // 0-3, inferred from category and season
}

/**
 * Compatibility score breakdown
 * 
 * Multi-dimensional scoring system for evaluating how well
 * items work together in an outfit.
 */
export interface CompatibilityScore {
  weatherFit: number;      // 0-1: How appropriate for current weather
  formalityAlignment: number; // 0-1: How well formality levels match
  colorHarmony: number;    // 0-1: How well colors work together
  capsuleCohesion: number; // 0-1: How well capsule tags align
  total: number;           // 0-1: Weighted average of all components
}

/**
 * Generated outfit with metadata
 * 
 * Represents a complete outfit generated by the algorithm,
 * including all selected items, scores, and generation context.
 */
export interface GeneratedOutfit {
  items: {
    jacket?: EnrichedItem;
    overshirt?: EnrichedItem;
    shirt: EnrichedItem;      // Required
    undershirt?: EnrichedItem;
    pants: EnrichedItem;      // Required
    shoes: EnrichedItem;      // Required
    belt?: EnrichedItem;
    watch?: EnrichedItem;
  };
  
  // Item IDs for saving to database
  itemIds: string[];
  
  // Compatibility scores
  scores: {
    overall: CompatibilityScore;
    pairwise: Record<string, CompatibilityScore>; // e.g., "shirt-pants"
  };
  
  // Swappable categories (have alternatives available)
  swappable: Record<string, boolean>;
  
  // Generation metadata
  weatherContext: WeatherContext;
  generatedAt: Date;
}

/**
 * Options for outfit generation
 * 
 * Input parameters for the generateOutfit function.
 */
export interface GenerationOptions {
  wardrobeItems: WardrobeItem[];
  weatherContext: WeatherContext;
  excludeItems?: string[]; // Item IDs to exclude (recently used)
  preferredCapsules?: string[]; // Preferred capsule tags for scoring boost
  preferredFormalityBand?: FormalityBand;
  preferredFormalityRange?: {
    min: number;
    max: number;
  };
  variationSeed?: string; // Optional deterministic seed to increase variety
  explorationLevel?: number; // 0-1, higher explores near-top matches more
}

/**
 * Options for item swapping
 * 
 * Input parameters for the swapItem function.
 */
export interface SwapOptions {
  currentOutfit: GeneratedOutfit;
  category: string; // Category to swap (e.g., 'shirt', 'pants')
  wardrobeItems: WardrobeItem[];
  weatherContext: WeatherContext;
}
